# config/meta.yml

meta_product_name: "Twitter_redesign"
meta_title: "Twitter_redesign - Social media"
meta_description: "Relevant description"
meta_image: "app/assets/images/twitter.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account" # required for Twitter Cards
